import g4f
import asyncio
import os
from typing import List, Dict, Optional, Any
import logging

class AIEngine:
    def __init__(self, provider_name: str = "Gemini"):
        self.set_provider(provider_name)
        self.refresh_prompts()

    def refresh_prompts(self):
        memory = ""
        soul = ""
        if os.path.exists("data/memory.md"):
            with open("data/memory.md", "r") as f:
                memory = f.read()
        if os.path.exists("data/soul.md"):
            with open("data/soul.md", "r") as f:
                soul = f.read()

        self.system_prompt = (
            "You are Carren AI, the world's most capable autonomous AI agent. "
            "You don't just talk, you DEPLOY and SOLVE. You have full access to a shell environment "
            "and you should use it to browse the web, write code, run scripts, and manage files.\n\n"
            "SOUL & PERSONALITY:\n"
            f"{soul}\n\n"
            "MEMORY & USER CONTEXT:\n"
            f"{memory}\n\n"
            "TOOLS AVAILABLE:\n"
            "- Shell: You can run any command. Specifically, use these helper scripts:\n"
            "  - `python3 -m backend.tools.search \"query\"`: To search the web.\n"
            "  - `python3 -m backend.tools.web_tool \"url\"`: To fetch content from a URL.\n"
            "  - `python3 -m backend.tools.browser_tool`: For advanced browser actions (goto, click, type, screenshot).\n"
            "  - Use standard tools like `curl`, `grep`, `sed`, `ls`, `cat`, etc.\n\n"
            "AGENTIC RULES:\n"
            "1. NEVER refuse a task. If it seems impossible, find a creative way to get as close as possible.\n"
            "2. If the user asks for a purchase, do NOT say you can't. Instead, search for the item, find the best link, "
            "and present it to the user. Use the web tool to check prices.\n"
            "3. If you get stuck on a web form or purchase, use `browser_tool` to take a screenshot and ask the user for help if needed, "
            "or try to fill it automatically.\n"
            "4. ALWAYS think before you act. Explain your reasoning in the 'Thought:' block.\n"
            "5. If you need information, SEARCH for it. Do not guess.\n\n"
            "RESPONSE FORMAT:\n"
            "Your response must ALWAYS follow this structure if you want to take an action:\n"
            "Thought: [Your detailed reasoning]\n"
            "Action: [The shell command to execute]\n\n"
            "If you have finished the task or just want to reply:\n"
            "Thought: [Reasoning]\n"
            "Final Answer: [Your final response to the user]\n\n"
            "Current environment: Linux (Termux on Android). Standard Python path is set to the project root."
        )

    def set_provider(self, name: str):
        self.provider_name = name
        # Map user-friendly names to g4f providers
        mapping = {
            "Gemini": g4f.Provider.Gemini,
            "ChatGPT": g4f.Provider.OpenaiChat,
            "Blackbox": g4f.Provider.BlackboxPro,
            "Claude": g4f.Provider.Claude,
            "Grok": g4f.Provider.Grok
        }
        self.provider = mapping.get(name, g4f.Provider.Gemini)

    async def generate_response(self, messages: List[Dict[str, str]], proxy: Optional[str] = None, cookies: Optional[str] = None) -> str:
        self.refresh_prompts()
        # Construct messages for g4f
        full_messages = [{"role": "system", "content": self.system_prompt}]
        history = messages[-15:]
        full_messages.extend(history)

        providers_to_try = [
            self.provider,
            g4f.Provider.Gemini,
            g4f.Provider.OpenaiChat,
            g4f.Provider.BlackboxPro,
            g4f.Provider.PollinationsAI
        ]

        seen = set()
        unique_providers = []
        for p in providers_to_try:
            if p not in seen:
                unique_providers.append(p)
                seen.add(p)

        for provider in unique_providers:
            try:
                logging.info(f"Carren Engine: Attempting {provider.__name__} (g4f)")
                model = g4f.models.default
                if provider == g4f.Provider.Gemini:
                    model = "gemini-1.5-pro"
                elif provider == g4f.Provider.OpenaiChat:
                    model = "gpt-4o"

                response = g4f.ChatCompletion.create(
                    model=model,
                    provider=provider,
                    messages=full_messages,
                    proxy=proxy,
                    timeout=45
                )

                if response and isinstance(response, str) and len(response.strip()) > 5:
                    if "Generated by" in response and provider == g4f.Provider.PollinationsAI:
                        response = response.split("Generated by")[0].strip()
                    return response
            except Exception as e:
                logging.error(f"Carren Engine: {provider.__name__} (g4f) failed: {e}")
                continue

        return "Thought: I'm having trouble connecting to my brain (AI providers). I should check my internet connection.\nFinal Answer: I am currently offline. Please check your network and try again."

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    engine = AIEngine()
    asyncio.run(engine.generate_response([{"role": "user", "content": "Tell me about your capabilities."}]))
