import g4f
import asyncio
from typing import List, Dict, Optional, Any
import logging
from backend.browser_engine import BrowserEngine

class AIEngine:
    def __init__(self, provider_name: str = "Gemini"):
        self.set_provider(provider_name)
        self.browser_engine = BrowserEngine()
        self.system_prompt = (
            "You are Manus AI, the world's most capable autonomous AI agent. "
            "You don't just talk, you DEPLOY and SOLVE. You have full access to a shell environment "
            "and you should use it to browse the web, write code, run scripts, and manage files.\n\n"
            "GUIDELINES:\n"
            "1. ALWAYS think before you act. Explain your reasoning clearly.\n"
            "2. If you need information you don't have, use 'curl' or 'wget' to fetch it or search for it.\n"
            "3. If a task requires multiple steps, break it down and execute them one by one.\n"
            "4. For complex coding, write the code to a file first, then run it.\n\n"
            "RESPONSE FORMAT:\n"
            "Your response must ALWAYS follow this structure if you want to take an action:\n"
            "Thought: [Your detailed reasoning]\n"
            "Action: [The shell command to execute]\n\n"
            "If you have finished the task or just want to reply:\n"
            "Thought: [Reasoning]\n"
            "Final Answer: [Your final response to the user]\n\n"
            "Current environment: Linux (Termux on Android). Be mindful of mobile constraints."
        )

    def set_provider(self, name: str):
        self.provider_name = name
        # Map user-friendly names to g4f providers
        mapping = {
            "Gemini": g4f.Provider.Gemini,
            "ChatGPT": g4f.Provider.OpenaiChat,
            "Blackbox": g4f.Provider.BlackboxPro,
            "Claude": g4f.Provider.Claude,
            "Grok": g4f.Provider.Grok
        }
        self.provider = mapping.get(name, g4f.Provider.Gemini)

    async def generate_response(self, messages: List[Dict[str, str]], proxy: Optional[str] = None) -> str:
        # Construct the last prompt with full context (since we can't easily pass full history to free web UIs)
        last_user_message = next((m["content"] for m in reversed(messages) if m["role"] == "user"), "")
        full_prompt = f"{self.system_prompt}\n\nHistory:\n"
        for m in messages[-10:]:
            full_prompt += f"{m['role'].capitalize()}: {m['content']}\n"
        full_prompt += f"\nUser Goal: {last_user_message}"

        # Try Headless Browser first for high-fidelity
        if self.provider_name in ["Gemini", "ChatGPT"]:
            try:
                logging.info(f"Manus Engine: Attempting Browser Engine ({self.provider_name})")
                if self.provider_name == "Gemini":
                    response = await self.browser_engine.fetch_gemini(full_prompt)
                else:
                    response = await self.browser_engine.fetch_chatgpt(full_prompt)

                if response and not response.startswith("Error:"):
                    return response
            except Exception as e:
                logging.error(f"Manus Engine: Browser fallback to g4f: {e}")

        # Fallback to g4f
        full_messages = [{"role": "system", "content": self.system_prompt}]
        history = messages[-15:]
        full_messages.extend(history)

        providers_to_try = [
            self.provider,
            g4f.Provider.Gemini,
            g4f.Provider.OpenaiChat,
            g4f.Provider.BlackboxPro,
            g4f.Provider.PollinationsAI
        ]

        seen = set()
        unique_providers = []
        for p in providers_to_try:
            if p not in seen:
                unique_providers.append(p)
                seen.add(p)

        for provider in unique_providers:
            try:
                logging.info(f"Manus Engine: Attempting {provider.__name__} (g4f)")
                model = g4f.models.default
                if provider == g4f.Provider.Gemini:
                    model = "gemini-1.5-pro"
                elif provider == g4f.Provider.OpenaiChat:
                    model = "gpt-4o"

                response = g4f.ChatCompletion.create(
                    model=model,
                    provider=provider,
                    messages=full_messages,
                    proxy=proxy,
                    timeout=45
                )

                if response and isinstance(response, str) and len(response.strip()) > 5:
                    if "Generated by" in response and provider == g4f.Provider.PollinationsAI:
                        response = response.split("Generated by")[0].strip()
                    return response
            except Exception as e:
                logging.error(f"Manus Engine: {provider.__name__} (g4f) failed: {e}")
                continue

        return "Thought: I'm having trouble connecting to my brain (AI providers). I should check my internet connection.\nFinal Answer: I am currently offline. Please check your network and try again."

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    engine = AIEngine()
    print(engine.generate_response([{"role": "user", "content": "Tell me about your capabilities."}]))
